### ISSUE TITLE
Some letters are not well mapped

### ISSUE THREAD

**Issue by xmontero** [wernerdweight/Canonicalizer#3] opened 2019-04-23 22:34 UTC
There are some not-mapped characters. For example the open accent over the a (à, À), the n-with-a-tilde (ñ, Ñ), the diereses-over-o (ö, Ö) and some more.

For example I'd expect "Àgata" to be mapped to "agata" and I get "-gata".

There are some more.

**Comment by xmontero** [comment] 2019-04-24 11:21
Maybe this could help:

* https://stackoverflow.com/questions/3371697/replacing-accented-characters-php
* https://developer.wordpress.org/reference/functions/remove_accents/

**Comment by wernerdweight** [comment] 2019-04-27 21:53
Hi, canonicalizer internally uses iconv which transliterates these characters well (`ö` and `à` are covered by unit tests). The problem might be caused by the implementation of iconv. Are you by any chance using musl implementation (default for alpine linux)?

If so, you can install different implementation (this code is to be placed into Dockerfile, if you`re not using docker, the process might be slightly different):
```
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

**Comment by xmontero** [comment] 2019-04-27 22:43
I tried it in a dockerized ubuntu `FROM ubuntu:18.04`

Connecting to this docker container...
If I do `apt list --installed | grep -i iconv` it shows no results.
If I do `php -i | grep -i iconv` I see the `iconv` PHP extension is actually ready to be used.

Maybe... Should I `apt-get install` some `iconv` manually system-wide because if not, any PHP consuming the `iconv` extension will throw "apparently good results" but "in fact, bad transliterations"?

If that's the case, 2 questions:

a) What should I install in ubuntu?
b) Would it be possible from the PHP to detect that "hey, php has iconv, but the underlaying layer does not" to allow the Transliterator class to throw a catchable exception?

**Comment by wernerdweight** [comment] 2019-04-28 16:34
Ok, tried that docker image with ubuntu 18.04 - it uses glibc implementation of iconv.

ad a) to use different implementation, you might need to recompile php - didn't try, not worth the hassle, i suppose;
ad b) yes that could be done, but I don't think there should be an exception because of underlaying library implementation - I'd rather fix the issue than delegate the solution to developers using these implementations;

I added  mapping for missing french and spanish characters, but I'm not sure I have correct pangrams (see https://github.com/wernerdweight/Canonicalizer/blob/master/Tests/CanonicalizerTest.php#L70 and https://github.com/wernerdweight/Canonicalizer/blob/master/Tests/CanonicalizerTest.php#L100) since I speak neither of them (I googled the current pangrams, I will gladly replace them with better ones, if you know better ones).

Can you try again with https://github.com/wernerdweight/Canonicalizer/releases/tag/1.1.2 (release I just made)?

**Comment by wernerdweight** [comment] 2019-05-02 14:45
Can I close this?

**Comment by xmontero** [comment] 2019-05-02 14:52
Not tested yet. I'd suggest to leave it open, please, until we do all the testing... Normal-work overload!

**Comment by wernerdweight** [comment] 2019-09-15 19:23
Closing this as it has been inactive for more than 4 months.

**Closed as completed by wernerdweight** 2019-09-15 19:23 UTC
Labels: bug
